### ISSUE TITLE
Can not recieve messages from discord

### ISSUE THREAD

**Issue by Synkstar** [Mestima/GM-Discord#1]
[ERROR] addons/gm-discord-master/lua/autorun/server/discord.lua:72: attempt to get length of local 'content' (a nil value)
1. onsuccess - addons/gm-discord-master/lua/autorun/server/discord.lua:72
2. unknown - lua/includes/modules/http.lua:29

**Comment by LSC1759** [comment]
Same issue, I get this spammed in console:
  [ERROR] lua/autorun/server/discord.lua:72: attempt to get length of local 'content' (a nil value)
  1. onsuccess - lua/autorun/server/discord.lua:72
   2. unknown - lua/includes/modules/http.lua:29

**Comment by Mestima** [comment]
Fixed. Thanks to [RanchTheDeer](https://github.com/RanchTheDeer)
