### ISSUE TITLE
attempt to get length of local 'content' (a nil value)

### ISSUE THREAD

**Issue by Scream145** [Mestima/GM-Discord#2]
[ERROR] addons/gmdiscord/lua/autorun/server/discord.lua:72: attempt to get length of local 'content' (a nil value)
  1. onsuccess - addons/gmdiscord/lua/autorun/server/discord.lua:72
   2. unknown - lua/includes/modules/http.lua:29

**Comment by ghost** [comment]
I have fixed this issue by modifying the request.php file.
Whilst the developer waits to process my pull request, you can use the patched file here:
https://github.com/RanchTheDeer/GM-Discord/blob/master/web/request.php

Simply replace the original file with this one on your webhost of choice and restart the Garry's Mod server.

**Comment by Mestima** [comment]
Fixed. Thanks to [RanchTheDeer](https://github.com/RanchTheDeer)
